[package]
name = "usbd_bulk_only_transport"
version = "0.1.0"
authors = ["cs2dsb <cs2dsb@gmail.com>"]
edition = "2018"
description = "usb-device implementation that provides a USB mass storage bulk only transport protocol"
categories = ["embedded"]
keywords = ["usb", "embedded", "no_std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/cs2dsb/stm32-usb.rs"
readme = "README.md"
documentation = "https://docs.rs/usbd_bulk_only_transport"
homepage = "https://github.com/cs2dsb/stm32-usb.rs/tree/master/firmware/usbd_bulk_only_transport"

[dependencies]
usb-device            = "0.3.1"
embedded-hal          = "0.2.7"
nb                    = "1.1.0"
typenum               = "1.17.0"
itm_logger            = { version = "0.1.2", default-features = false }
usbd_mass_storage     = { version = "0.1.0", path = "../usbd_mass_storage" }
packing               = { version = "0.2.0", path = "../packing/packing" }

[features]
trace-bot-headers = []
trace-bot-states = []
trace-bot-bytes = []
trace-bot-zlp = []
trace-bot-buffer = []
trace-usb-control = [ "usbd_mass_storage/trace-usb-control" ]
trace-all = [ "trace-bot-headers", "trace-bot-states", "trace-bot-bytes", "trace-bot-zlp", "trace-bot-buffer",
              "trace-usb-control" ]
